apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: frontend-probe
  namespace: default
  labels:
    release: monitoring
spec:
  jobName: frontend-probe
  interval: 15s
  module: http_2xx
  prober:
    url: blackbox-prometheus-blackbox-exporter:9115
  targets:
    staticConfig:
      static:
      - http://frontend.online-boutique.svc.cluster.local